// Trip data — Japan: Tokyo / Kyoto / Osaka
window.TRIP_DATA = {
  title: "Japan in May",
  subtitle: "Tokyo · Kyoto · Osaka",
  dates: "May 12 — May 21, 2026",
  daysCount: 9,
  cover: "Mt. Fuji",
  budget: { spent: 1840, total: 3200, currency: "USD" },
  cities: [
    { id: 1, name: "Tokyo",  nights: 3, dates: "May 12 — May 15", color: "#d2552c", x: 78, y: 52 },
    { id: 2, name: "Hakone", nights: 1, dates: "May 15 — May 16", color: "#c89968", x: 70, y: 60 },
    { id: 3, name: "Kyoto",  nights: 3, dates: "May 16 — May 19", color: "#2d4a3e", x: 36, y: 64 },
    { id: 4, name: "Osaka",  nights: 2, dates: "May 19 — May 21", color: "#5a3a4a", x: 28, y: 70 },
  ],
  days: [
    { day: 1, date: "Tue · May 12", city: "Tokyo",
      activities: [
        { id: "a1", time: "06:25", end: "07:45", title: "Haneda landing",
          kind: "Flight", note: "JAL 002 · LAX → HND", icon: "plane",
          tone: "moss", img: "AIRPORT",
          legAfter: { mode: "taxi", distance: "18 km", duration: "32 min", label: "Taxi to hotel" } },
        { id: "a2", time: "10:00", end: "12:00", title: "Hotel check-in",
          kind: "Stay", note: "Hoshinoya Tokyo · Otemachi", icon: "bed",
          tone: "sand", img: "RYOKAN LOBBY",
          legAfter: { mode: "subway", distance: "2.4 km", duration: "9 min", label: "Marunouchi line · 1 stop" } },
        { id: "a3", time: "13:30", end: "16:00", title: "Tsukiji outer market",
          kind: "Food", note: "Uni, tamago, knife shopping", icon: "fork",
          tone: "accent", img: "MARKET STALL",
          legAfter: { mode: "walk", distance: "950 m", duration: "12 min", label: "Walk through Ginza" } },
        { id: "a4", time: "19:30", end: "22:00", title: "Omakase at Sushi Saito",
          kind: "Dinner", note: "Reserved · 9 courses", icon: "fork",
          tone: "plum", img: "SUSHI COUNTER" },
      ]},
    { day: 2, date: "Wed · May 13", city: "Tokyo",
      activities: [
        { id: "b1", time: "08:00", end: "09:30", title: "Meiji Jingu walk",
          kind: "Walk", note: "Forest shrine · Yoyogi", icon: "leaf",
          tone: "moss", img: "TORII GATE",
          legAfter: { mode: "subway", distance: "6.1 km", duration: "18 min", label: "Hibiya line to Roppongi" } },
        { id: "b2", time: "11:00", end: "13:00", title: "teamLab Borderless",
          kind: "Museum", note: "Azabudai Hills · book ahead", icon: "spark",
          tone: "plum", img: "DIGITAL ART",
          legAfter: { mode: "walk", distance: "1.8 km", duration: "22 min", label: "Walk through Omotesando" } },
        { id: "b3", time: "15:00", end: "17:00", title: "Shibuya & Cat Street",
          kind: "Walk", note: "Coffee at Fuglen", icon: "cup",
          tone: "sand", img: "STREET CROSSING",
          legAfter: { mode: "taxi", distance: "4.3 km", duration: "15 min", label: "Taxi to Shinjuku" } },
        { id: "b4", time: "20:00", end: "23:00", title: "Golden Gai bar crawl",
          kind: "Nightlife", note: "Shinjuku · ¥¥", icon: "moon",
          tone: "accent", img: "NEON ALLEY" },
      ]},
    { day: 3, date: "Thu · May 14", city: "Tokyo",
      activities: [
        { id: "c1", time: "09:30", end: "12:00", title: "Nezu Museum + garden",
          kind: "Museum", note: "Aoyama · tea", icon: "spark",
          tone: "moss", img: "JAPANESE GARDEN",
          legAfter: { mode: "subway", distance: "5.6 km", duration: "16 min", label: "Chiyoda → Nippori line" } },
        { id: "c2", time: "14:00", end: "16:30", title: "Yanaka old town",
          kind: "Walk", note: "Sendagi to Nippori", icon: "leaf",
          tone: "sand", img: "OLD ALLEY" },
      ]},
    { day: 4, date: "Fri · May 15", city: "Hakone",
      activities: [
        { id: "d1", time: "09:00", end: "11:30", title: "Romance Car to Hakone",
          kind: "Train", note: "Shinjuku → Hakone-Yumoto", icon: "train",
          tone: "sand", img: "TRAIN WINDOW",
          legAfter: { mode: "taxi", distance: "8 km", duration: "20 min", label: "Taxi up to Gora" } },
        { id: "d2", time: "14:00", end: "17:00", title: "Open-Air Museum",
          kind: "Museum", note: "Picasso pavilion", icon: "spark",
          tone: "plum", img: "SCULPTURE PARK",
          legAfter: { mode: "walk", distance: "600 m", duration: "8 min", label: "Walk to ryokan" } },
        { id: "d3", time: "18:30", end: "21:00", title: "Onsen + kaiseki",
          kind: "Stay", note: "Gora Hanaougi", icon: "bed",
          tone: "moss", img: "ONSEN BATH" },
      ]},
    { day: 5, date: "Sat · May 16", city: "Kyoto",
      activities: [
        { id: "e1", time: "08:00", end: "11:00", title: "Shinkansen to Kyoto",
          kind: "Train", note: "Nozomi 7 · 220 km/h", icon: "train",
          tone: "accent", img: "BULLET TRAIN" },
      ]},
  ],
  packing: [
    { cat: "Documents", items: [
      { name: "Passport + JR Pass", on: true },
      { name: "Insurance card", on: true },
      { name: "Hotel bookings printed", on: false },
    ]},
    { cat: "Clothes", items: [
      { name: "5x linen tees", on: true },
      { name: "Light rain shell", on: false },
      { name: "Walking shoes", on: true },
      { name: "Onsen-friendly socks", on: false },
    ]},
    { cat: "Tech", items: [
      { name: "Type-A → C adapter", on: false },
      { name: "Pocket WiFi pickup code", on: true },
      { name: "Camera + 35mm lens", on: false },
    ]},
  ],
  budget_categories: [
    { name: "Stays",    spent: 980, total: 1400, color: "var(--moss)" },
    { name: "Food",     spent: 420, total: 700,  color: "var(--accent)" },
    { name: "Transit",  spent: 280, total: 600,  color: "var(--sand)" },
    { name: "Tickets",  spent: 90,  total: 300,  color: "var(--plum)" },
    { name: "Misc",     spent: 70,  total: 200,  color: "var(--sky)" },
  ],
};

window.OTHER_TRIPS = [
  { name: "Lisbon weekend", dates: "Mar 14 — Mar 17", days: 4, status: "Past", img: "AZULEJOS" },
  { name: "Iceland ring road", dates: "Aug 02 — Aug 12", days: 11, status: "Upcoming", img: "GLACIER" },
  { name: "Bali surf", dates: "Nov 18 — Nov 28", days: 11, status: "Idea", img: "REEF BREAK" },
];
